- engine.go
- session.go
- statement.go
实现对表达式赋值语句的支持：
```go
func (engine *Engine) SetExpr(column string, expression string) *Session
```
MySQL示例（更新用户最后活跃时间）：
```go
engine.Id(id).SetExpr("ActiveTime", "UNIX_TIMESTAMP()").Update(&user)
```
> implement SetExpr()

- statement.go
修复mysql下 select id,name from user where type=1 group by login_time 被替换成 select id,name from user where type =1 group by id,name的问题
> 修复mysql下group by 字段被替换成查询的column的问题

- helpers.go
Hi there,
I've got a bug regarding invalid memory access because a passing value has gone when access.
It's occurred from the following commit. (11d36774e9cd90eb22ebd2727868c09928d2702a)
So, I add nil-checked statement.
Thx
(Please check the PR ASAP! :bow: )
> Fix to refer invalid memory access on helpers.go

- engine.go
参考帮助文档 [自动映射的规则](http://gobook.io/read/go-xorm/manual-zh-cn/chapter-02/4.columns.html) 中的说明
> 如果field名称为Id而且类型为int64并且没有定义tag，则会被xorm视为主键，并且拥有自增属性。如果想用Id以外的名字或非int64类型做为主键名，必须在对应的Tag上加上xorm:"pk"来定义主键，加上xorm:"autoincr"作为自增。这里需要注意的是，有些数据库并不允许非主键的自增属性。
因此在使用`core.GonicMapper`时，忽略了ID主键
> bugfix #213

- statement.go
package test
import (
_ "github.com/go-sql-driver/mysql"
"github.com/go-xorm/xorm"
"testing"
)
type Model struct {
Id   int64
Tags *Tag `xorm:"tag_id varchar(255) index"`
}
type Tag struct {
Id string `xorm:"pk unique varchar(255)"`
}
func Test_Test(t *testing.T) {
orm, err := xorm.NewEngine("mysql", "root:GooglE@/test?charset=utf8")
if err != nil {
t.Error(err)
}
if err = orm.Sync2(new(Model), new(Tag)); err != nil {
t.Error(err)
}
orm.Insert(&Tag{Id: "USA"})
orm.Insert(&Tag{Id: "UK"})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}})
orm.Delete(&Model{Tags: &Tag{Id: "USA"}}) // Tag主键为非数字时，此处报错
}
> fix non-int pk issues

- statement.go
```go
package test
import (
_ "github.com/go-sql-driver/mysql"
"github.com/go-xorm/xorm"
"testing"
)
type Model struct {
Id    int64
Tags  *Tag   `xorm:"tag_id varchar(255) index"`
Title string `xorm:"varchar(255)"`
}
type Tag struct {
Id string `xorm:"pk unique varchar(255)"`
}
func Test_Test(t *testing.T) {
orm, err := xorm.NewEngine("mysql", "root:@/test?charset=utf8")
if err != nil {
t.Error(err)
}
if err = orm.Sync2(new(Model), new(Tag)); err != nil {
t.Error(err)
}
orm.Insert(&Tag{Id: "USA"})
orm.Insert(&Tag{Id: "UK"})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}, Title: "Model 1"})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}, Title: "Model 2"})
orm.Insert(&Model{Tags: &Tag{Id: "USA"}, Title: "Model 3"})
//orm.Delete(&Model{Tags: &Tag{Id: "USA"}}) // Tag主键为非数字时，此处报错 …
```
> func buildUpdates has same issue, fixed

- mssql_dialect.go
MSSQL: Also use doublequote as quote char to avoid problems.
> MSSQL: Also use doublequote as quote char to avoid problems

- engine.go
- helpers.go
- session.go
- statement.go
This PR added method `Nullable()` to add null valued colums for UPDATE.
For INSERT, we can insert null value using `Omit()`, but not for UPDATE.
So using `Nullbale()` and set columns which could be null value,
null value is set when the value is `zero-value` and `nullable`.
For example, use like below,
```go
type Example struct {
Id     int64     `xorm:"pk"`
Field1 string    `xorm:"default null"`
Field2 int64     `xorm:"default null"`
Field3 time.Time `xorm:"default null"`
NoNull int64     `xorm:"not null"`
}
func example(){
row := &Example{}
session := engine.NewSession()
defer session.Close()    // * updated 2015-06-11
session.
Where("id = ?", id).
Nullable("field1").
Update(row)
// => UPDATE example SET field1 = null WHERE id = ?
session.
Where("id = ?", id).
Cols("field1", "field2", …
```
> Add feature to update with null for non pointer value

- rows.go
- session.go
This PR added method `LastSQL()` and `saveLastSQL()` to get and store information of last query on the session.
To achieve this, `session.Engine.logSQL()` is moved into  `session.saveLastSQL()`.
> Added feature for storing lastSQL query on session

- mssql_dialect.go
- session.go
- sqlite3_dialect.go
- statement.go
This PR adds feature for SELECT .. FOR UPDATE, to lock the rows from other session.
use this method whenever before select, `... FOR UPDATE` is added the select statement.
- `Session.ForUpdate()`
quick usage like below,
```go
func DoForUpdate(engine *Engine, id int64){
engine.ShowSQL = true
user := new(User)
s := engine.NewSession()
s.Begin()
s.Where("id = ?", id)
s.ForUpdate()
has, err := s.Get(user)
// process on the transaction continues...
}
```
> Added feature for SELECT ... FOR UPDATE

- helpers.go
This PR changed checking zero-value for struct to use `IsZero() bool` in `isZero()` helper function.
Every struct which has `IsZero() bool` can be evaluated as zero-value or not.
This is useful when using custom time struct for time field.
> Modified time.IsZero() to use interface

- sqlite3_dialect.go
fix a bug: when use xorm reverse tool for sqlite3 , if table have a struct like this UNIQUE(xx, xx) , reverse will fail.
> fix a bug: when use xorm reverse tool for sqlite3 , if table have a struct like this UNIQUE(xx, xx) , reverse will fail.

- statement.go
This PR fixed invalid sql statement when empty slice is passed to `statement.In()`.
```go
var emptyArgs []string
s.Where("col1 > ?", 0)
s.In("col2", emptyArgs)
s.Find(val)
// before: SELECT * FROM table WHERE `col1` > 0 AND `col2` IN ();
// after: SELECT * FROM table WHERE `col1` > 0;
```
> Ignore empty args statement.In()

- mysql_dialect.go
Fail to initialize ORM engine: sync database struct error: Error 1061: Duplicate key name …
Supported DBMS:
* Percona-Server 5.6
* MariaDB 5.5/10.0/10.1
```
+--------+--------------+------+------------+---------+--------------------------------------------------------------------------------------------------+
| Engine | Transactions | XA   | Savepoints | Support | Comment                                                                                          |
+--------+--------------+------+------------+---------+--------------------------------------------------------------------------------------------------+
| TokuDB | YES          | YES  | YES        | YES     | Percona TokuDB Storage Engine with Fractal Tree(tm) Technology                                   |
| InnoDB | YES …
```
> Preventing the creation of duplicate index TokuDB

- engine.go
Correctly handle columns being passed in the format
"table.column"
fixes #369
> quote "."(periods) in column name.

- statement.go
It seems that `Join()` overwrites args from previous `Join()` calls.
> Accumulate args when using Join() multiple times

- session.go
**Change 1**
Fix panic when formatting error: `reflect.TypeOf(v)` returns `nil` if `v` is `nil`.
**Change 2**
Support pointers to type aliases. Example:
```
type MyInt int
type MyStruct struct {
i1 MyInt   // already works
i2 *int    // already works
i3 *MyInt  // didn't work before this PR
}
```
**Test**
https://github.com/go-xorm/tests/pull/10
> Support pointers to type aliases

- engine.go
- session.go
- statement.go
With these changes, SELECT always lists column names, even with JOINs,
instead of using `SELECT *`.
This also eliminates xorm warnings "table FOO has no column BAR" appearing when xorm uses `SELECT *` and retrieves  superfluous fields.
**Changelog**
* go-xorm/core#13: add new field `Column.TableName` and fill it when creating column in `mapType()`
* add new field `Statement.OutTable` and fill it in `Get()` and `Find()`
* add `buildColName()` function and `colName()` wrapper that uses `Column.TableName` if available or default table name otherwise, and use them everywhere
* move all column string related code to `genColumnStr()` and use it everywhere
* go-xorm/tests#11: add more tests for extends
**OutTable**
Unlike `RefTable`, `OutTable` will always contain *output* table.
E.g. in this …
> Always generate column names, don't use * even if join

- engine.go
@lunny 
logging of a function pointer is not human-friendly.
```bash
[xorm] [info]  2016/05/23 02:26:29.734657 PING DATABASE0x4647d0
```
So, I fixed.
```bash
[xorm] [info]  2016/05/23 02:31:12.277675 PING DATABASE mysql
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-xorm/xorm/399)
> Fixed driver-name logging

- engine.go
- session.go
This fixes a problem with timezone conversion when the database's timezone differs from the xorm client's timezone.
See https://github.com/go-xorm/xorm/issues/419
> Allow the database's timezone to be specified. 

- engine.go
When panic/recover in *Engine.autoMapType, Engine.mutex is Locked and never Unlocked.
This PR fix this.
> use defer prepareing for panic/recover

- mssql_dialect.go
Using uuid with mssql results in an error, that the type uuid can not be found by mssql. This is resolved by mapping uuid to varchar.
> Using uuid with mssql

- helpers.go
- session.go
These changes replace usage of:
* `xorm.equalNoCase` (defined in `helpers.go`) onto `strings.EqualFold`.
* `strings.ToLower` for case insensitive string comparison onto `strings.EqualFold`.
> `strings.EqualFold` reports whether `s` and `t`, interpreted as UTF-8 strings, are equal under Unicode case-folding.
https://golang.org/pkg/strings/#EqualFold
> Case insensitive string comparison using strings.EqualFold

- examples/sync.go
- mssql_dialect.go
- mysql_dialect.go
- oracle_dialect.go
- postgres_dialect.go
- sqlite3_dialect.go
Fixed following go vet warnings:
```
$ go vet -v ./...
mssql_dialect.go:374: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
mssql_dialect.go:376: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
mssql_dialect.go:378: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
mssql_dialect.go:381: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
mysql_dialect.go:376: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
oracle_dialect.go:736: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
oracle_dialect.go:738: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields
oracle_dialect.go:740: github.com/go-xorm/core.SQLType composite literal uses unkeyed fields …
```
> Fix go vet warnings

- engine.go
- statement.go
- statement_test.go
Rewritten `statement.genColumnStr` for columns string generation via `bytes.Buffer` instead of `strings.Join`
Up to 30% faster, 50% less memory usage and 5 times less allocations per operation (see benchmarks below).
Affects on `session.Find` and `session.Get` on simple queries (i.e. without GroupBy and Join).
<br>
Benchmarks (9 columns):
```
BenchmarkColumnsStringGeneration_Join-4		500000	      2748 ns/op    	 784 B/op	      16 allocs/op
BenchmarkColumnsStringGeneration_Buffer-4      1000000	      1941 ns/op    	 352 B/op	       3 allocs/op
```
> Columns string generation via bytes.Buffer (statement.genColumnStr)

- mssql_dialect.go
- mysql_dialect.go
- oracle_dialect.go
- postgres_dialect.go
Fix warnings from `golint` regarding error text formatting:
```
$ golint ./... | grep fmt.Errorf
mssql_dialect.go:383:22: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
mysql_dialect.go:378:21: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
oracle_dialect.go:760:21: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
postgres_dialect.go:993:21: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
```
> golint: replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)

- helpers.go
- session.go
- statement.go
- statement_test.go
Columns in the maps (such as `statement.columnMap`, `statement.mustColumnMap`, `statement.nullableMap`) are placed in lowercase.
Each time, when there is need to get any flag from map, name of the column converts to lowercase. Every calling of `strings.ToLower` makes new allocations.
As an example -  all columns in function `statement.buildConds`are checking via `statement.mustColumnMap` (which is filled up only for update statements). This operation makes 2*columns_count unnecessary allocations.
Simple way to fix it - is to make helper method for flag getting from the map via case insensitive keys comparison.
Benchmarks of the current realization and offered way above (simple flag getting from the map, 9 columns):
```
BenchmarkGetFlagForColumnWithToLower_ContainsKey-4   	 1000000 …
```
> Getting flag for the column via helper method

- mssql_dialect.go
According to [https://msdn.microsoft.com/en-us/library/ms187993.aspx](https://msdn.microsoft.com/en-us/library/ms187993.aspx) the column type text should not be used any more in mssql. Furthermore the type text is causing problems as one can see in this pull request to gogs: [#3772](https://github.com/gogits/gogs/pull/3772).
To circumvent this problems text should be mapped to varchar(max) as proposed in the link to the msdn above.
> Using varchar(max) instead of text in mssql

- engine.go
I fixed a bug which ignores the given `*time.Location` by argument of the following function;
``` go
func (engine *Engine) formatTime(tz *time.Location, sqlTypeName string, t time.Time) (v interface{}) {
// ...
if tz != nil {
t = engine.TZTime(t)
}
```
The above code has no meanings of `tz`. So, I did add some code to handle `tz` correctly.
``` go
if tz != nil {
+       t = t.In(tz)
+   } else {
t = engine.TZTime(t)
}
```
It has a tiny bug that happened when I try to switch timezone in my app.
see also;
``` go
func (engine *Engine) formatColTime(col *core.Column, t time.Time) (v interface{}) {
if col.DisableTimeZone {
return engine.formatTime(nil, col.SQLType.Name, t)
} else if col.TimeZone != nil {
return engine.formatTime(col.TimeZone, col.SQLType.Name, t)
}
return …
```
> Apply the given location instead of engine.location

- session_delete.go
- session_update.go
Fix some bugs from https://github.com/go-gitea/gitea/issues/677#issuecomment-273945141
cc @lunny
> fix: execute after hook.

- session_insert.go
- session_insert_test.go
是因为如果slice的数据比较大，超出了sql的执行字符长度。那我将slice做了切分，并按认为可执行的长度[]interface{}传入到insertMulti中，xorm version: 769f6b3ae663248e8f1b1d8fecbe1eb26ac77ac7 是支持的。到了现在的版本不支持，加上reflect.ValueOf(Value.Interface())即可，本人已测过
> update for valueof interface

- helpers.go
- session_update_test.go
When use `Cols` with `Incr` or `Decr`, it will generate two update sets. This PR will fix that. When `Cols` with `Incr` or `Decr`. The same column on `Cols` will be ignored.
> fix bugs cols with incr when update

- engine.go
I don't see `nil` and empty strings in log. I suggest the next changes 
**Before**
```
INSERT INTO `dish` (`dish_id`,`restaurant_id`,`name`,`source`,`entry_id`,`created_by`,`menu_id`,`category`,`description`,`price`,`score`,`flog_count`,`approve`,`activated`,`created_at`,`updatated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [59639fb56d9d9437b707a434 58a313719fee7b336da70c45 Chocolate Mousse Torte fsqi 51339970   Dessert Seasonal berry sauce 0 0 0 1 false 2017-07-10 18:39:33 2017-07-10 18:39:33]
```
**After**
```
INSERT INTO `dish` (`dish_id`,`restaurant_id`,`name`,`source`,`entry_id`,`created_by`,`menu_id`,`category`,`description`,`price`,`score`,`flog_count`,`approve`,`activated`,`created_at`,`updatated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) …
```
> More clear log

- session.go
- session_test.go
This also removed the unused code `session.Init()` in `session.Close()`
> tests for close and add IsClosed() method

- processors.go
- processors_test.go
- rows.go
- session.go
- session_find.go
- session_get.go
This PR adds a new processor `AfterLoad`, it will be called after an object loaded from database and rows closed (except when you call `Rows`). That means we can reuse the session on `AfterLoad` like https://github.com/go-xorm/xorm/pull/743/files#diff-743fb9433abb258bf1fd1d441499f749R982 .
> improve processors

- session.go
数据库中的 json 理应被 golang 端的 string 类型支持，以前使用 xorm 生成的对象就是 json 映射到 golang string 类型的。
> add string support

- dialect_postgres.go
- dialect_postgres_test.go
Fixes #775 This fixes two problems - the postgres dialect can parse a password with spaces. If an error occurs the Parse func returns an error instead of panicking.
There are some problems still however:
- The Parse function cannot handle symbols like `#` in a password but we handle that in Grafana (where I found this bug) by escaping everything before creating the connection string. 
The code seems to be based on code from pq from 5 year ago. The current version of pq does a lot more checks when parsing connection strings to handle all these cases - see this [PR](https://github.com/lib/pq/pull/133) that fixed the panic problem in pq.
> Postgres dialect parse password with spaces (#775)

- error.go
`Not found table` => `Table not found`
`Field is not exist` => `Field does not exist`
etc..
> grammar mistakes in output error message

- dialect_postgres.go
- dialect_postgres_test.go
- xorm.go
The Pgx driver should be changed，so that it can work with pgx's stdlib properly
FYI: https://github.com/jackc/pgx/blob/master/stdlib/sql.go#L137
pgx provide has customized the leading 9 bytes of the dsn to provide a mechanism to config the connection, EG: set `PreferSimpleProtocol = true`, However, when using this mechanism, the `Parse` process of xorm will be failled.
xorm 中 pgx driver的`Parse`方法会导致不能使用`pgx` stdlib 包中的`ConnConfig`, 有一些pgx的配置比如设置`PreferSimpleProtocol` 为 `true` 就没办法去做， 所以提供了一个新类去处理这件事情， 在`Parse` 阶段直接将将9个字符根据pgx的规则扔掉， 保证能Parse通过
> Change pgx driver

- session_update.go
- session_update_test.go
For example,
```
type Object struct {
Id        int64
DeletedAt time.Time `xorm:"deleted"`
}
```
Now I want to restore a deleted record, if I use
```
engine.ID(1).Unscoped().Nullable("deleted_at").Update(&Object{})
```
It's OK, but if I use
```
engine.ID(1).Unscoped().Cols("deleted_at").Update(&Object{})
```
It has no effect.
I think the effect of these two way should be consistent.
> Fix genUpdateColumns() should not ignore soft delete column when unscoped

- session_get.go
Currently errors while data is being read are being swallowed and result in a truncated result set, this fixes that and properly returns an error and not an incomplete result.
> Propagate errors from SQL row reading

- session_delete.go
- session_find.go
- session_get.go
Should use session.statement.TableName() instead of table.Name. When one table's name is different from the struct's name, table.Name will be wrong.
>  fix session_find & session_get getCacher param error

- dialect_mssql.go
Before this commit the Default would be reset to 0 every time it is not true. This results in an issue when true is converted to 1 and 1 is not true, resulting in a conversion to 0.
This should also fix https://github.com/go-gitea/gitea/pull/4282.
> Implementing elseif for conversion of Default

- dialect_postgres.go
- engine.go
Fixing go-gitea/gitea#5651 
* UUID and BOOL type shouldn't have a length field
* Incorrect quoting cause that the column names are selected instead of the column values
> Fix exporting values into Postgres

- session_insert.go
- session_insert_test.go
This PR will add support to `Insert` like below:
```Go
cnt, err := testEngine.Table("table").Insert(map[string]interface{}{
"width":  20,
"height": 10,
"name":   "lunny",
})
```
> Add insert map support

- dialect_postgres.go
- dialect_postgres_test.go
Unsupport [Indexes on Expressions](https://www.postgresql.org/docs/11/indexes-expressional.html)
Fixed #1183
> fix excute GetIndexes error with sepcial postgresql index

- session_exist.go
oracle中没有 limit 关键字， 使用 rownum
> fix bug in oracle： engine.Table(tablename).Exist()

- go.mod
- go.sum
- migrate/migrate_test.go
Testify is included twice in two different ways. This consolidates to single import path.
cc: @kolaente (this hopefully resolves the go module issues you have had with my libraries)
> clean up go modules

- session_exist.go
`user` in `PostgreSQL` is a reserved word and needs to quote it.
> add quote within the table name

- engine.go
- interface.go
- session_query.go
- session_raw.go
Fix spelling inconsistency :
`sqlorArgs` => `sqlOrArgs`
Fix typo :
`sqlOrAgrs` => `sqlOrArgs`
> Fix spelling inconsistency and typos

- engine.go
- tag.go
- tag_extends_test.go
Added new syntax like `extends('Prefix')` to enable matching all
extended fields as `PrefixFieldName`.
Close go-xorm/xorm#1270
> Allow adding prefix for fields with `extends` tag

- statement.go
In xorm implementation, the statement can't know the struct joined in, so use '\*' instead of the columns from target struct. But '*' can't be use in a subquery here (https://github.com/go-xorm/xorm/blob/v0.7.4/statement.go#L1160). Check the `columnStr` before use it .
> fix issue #448

- engine.go
- helpers.go
- helpers_test.go
- session_insert.go
- session_update.go
- session_update_test.go
- statement.go
- statement_test.go
> Remove QuoteStr() usage

- README.md
> Document for FindAndCount()

- session_get.go
- session_get_test.go
- tag_test.go
> fix error when get null var

- session_insert.go
- session_insert_test.go
> Add insert select where support

- dialect_postgres.go
Remove unuse code in `func (db *postgres) GetColumns(tableName string) ([]string, map[string]*core.Column, error)`
> Remove unuse get cols code

- dialect_mssql.go
- session_insert.go
- session_insert_test.go
> fix bug when insert multiple slices with customize table name

- dialect_mssql.go
- dialect_sqlite3.go
- tag_test.go
- xorm_test.go
> Fix wrong dbmetas

- engine.go
- session_schema.go
This PR will reduce to query columns when run `Sync2`. Before this PR, it will load all the tables and columns. But on this PR, it will load columns only the tables need to synchronize. 
This should fix #1377
> Improve sync2

- session_schema.go
- session_schema_test.go
> Fix sync2 with custom table name

- session_get_test.go
- statement.go
> fix bug when query map condtion with no quote
