session.go
使 `SetExpr()` 对插入操作也有效。
示例：
```go
user := new(User)
user.Name = "myname"
affected, err := engine.SetExpr("RegTime", "UNIX_TIMESTAMP()").Insert(user)
```
=> make SetExpr() available for insert op

engine.go, session.go, statement.go
modify base on lastest version of xorm
=> for oracle support

helpers.go
Support another types: float32, float64 and bool type field for null update (#256)
=> Support float and bool for nullable update

postgres_dialect.go
防止数据库中，存在多个schema同表名，不同的字段属性的污染
=> 修改GetColumns函数

pq_driver.go
http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
btw：我说怎么我的openshift的还在报错，原来我忘记pr了，，，
=>  PG connection URIs

session.go, statement.go
I assume several `Statement` methods are in `session.go` by mistake.
=> Move statement methods to statement.go

engine.go
refactored engine.go
Remove unused method.
```bash
$ cd path/to/xorm
$ grep -r "mapping(" ./ | wc -l
0
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-xorm/xorm/425)
=> Remove unused method

engine.go
=> Modify extract LOCALE sign from tags

engine.go
refactored engine.go
Remove unused method.
```bash
$ git grep -c "quoteColumn" ./ | wc -l
0
```
=> Remove quoteColumn method

README_CN.md
=> fix README_CN.md syntax

statement.go
=> Fix typo at NotIn comment

statement.go
some database very important, such as pg!
=> fix IN and NotIN SQL not add quote

statement.go
auto judge exist or not quote，then add or ignore
=> auto judge exist or not quote，then add or ignore

.gitignore, migrate/migrate.go, migrate/migrate_test.go
This is a port from https://github.com/go-gormigrate/gormigrate
=> Add migrate package for schema versioned migrations

session_sum.go
bug fix for SumsInt return empty slice
=> bug fix for SumsInt return empty slice

engine.go, session_schema.go, statement_test.go, tag.go, xorm.go
This PR makes an uniform method to handle xorm tag and prepare for customerize tag support. Related with #404
=> Handle xorm tags via tagHandler prepared for customerize tag support

statement.go
=> fix distinct & top conflict on mssql

session_insert.go, session_pk_test.go
=> fix insert single pk column table failed

dialect_sqlite3.go, doc.go, engine.go, session_pk_test.go, xorm.go
=> fix bug and add set conn max lifetime

doc.go, session_sum.go, session_sum_test.go
This PR implemented Count with custom SQL.
=> add custom SQL count support

session_get_test.go
=> add test for get slice

rows.go, session.go, session_get.go
This PR will close rows as we can.
=> close rows if possible

README.md, README_CN.md
I have developed the [Xorm adapter](https://github.com/casbin/xorm-adapter) for Casbin. It uses Xorm to store the access control policy rules. I'd like to add it to the README list. Thanks!
=> add Xorm Adapter for Casbin as cases

session_update.go, session_update_test.go
=> improve update error when no conent to be updated

session_tx.go, session_tx_test.go
=> Revert "support reuse session to transaction"

session_stats.go, session_stats_test.go, statement.go
Support `total, err = testEngine.Where(cond).Table("userinfo_count").Count()`
=> improve count usage

session_update_test.go, statement.go
=> fix bug on update

xorm.go
=> fix bug on new engine

engine.go, session_schema.go
=> Reduce sessions on Sync

cache_lru.go, cache_lru_test.go, cache_memory_store_test.go, cache_test.go, circle.yml, processors_test.go, session_cols_test.go, session_delete.go, session_delete_test.go, session_find.go, session_get.go, session_insert.go, session_insert_test.go, session_pk_test.go, session_query_test.go, session_schema_test.go, session_stats_test.go, session_update.go, session_update_test.go, statement.go, test_mssql_cache.sh, test_mymysql_cache.sh, test_mysql_cache.sh, test_postgres_cache.sh, test_sqlite_cache.sh, time_test.go, xorm_test.go
=> fix bug on cache delete

cache_test.go, session_find.go
=> fix bug on cache specify table name

dialect_postgres.go, session_query.go, session_query_test.go
=> fix querystring bit type

convert.go, session.go, session_convert.go, session_find_test.go
=> Fix find bit

session_insert_test.go, session_update_test.go
=> Add more tests for created int64

tag_test.go
=> Add time test

xorm_test.go
=> fix default go test

session_get.go, xorm.go
=> fix bugs on Get

session_update.go, session_update_test.go
=> fix conflicts between Cols and updated

session_update_test.go
=> Add test for updated created

session_delete_test.go
=> Add test for unscoped delete

engine.go, session_iterate.go, session_iterate_test.go, statement.go
=> Add buffer Iterate support

session_insert.go
defer handleAfterInsertProcessorFunc(bean)
=> after call AfterInsert

error.go, session_update.go, session_update_test.go, statement.go
=> Add support for map[string]interface{} as condition on Update and Where

context.go, context_test.go
=> Add PingContext support for go1.8+

README.md
There was a missing dot on sample code
=> Add a missing dot

statement.go
In the synchronous table, Add fields to add comments. support mysql
=> mysql add column comment

engine.go, interface.go, session_query.go
Like `Query`, `QueryString` and `QueryInterface` also could use `Where`, `And` and other conditions.
=> QueryString and QueryInterface supports composite conditions

session_get.go, session_get_test.go
=> Support Get sql.Nullxx

session_query.go, session_query_test.go
Will resolve go-xorm/builder#9
=> Query add builder support

session_exist.go
will resolved #831 and fix go-gitea/gitea#3403
=> Fix Exist bug when using on MSSQL resolved #831

migrate/migrate.go
=> Fix migrate migrationDidRun bug on postgres

session_find.go, session_find_test.go
=> fix findandcount bug with order

engine.go
=> chore(postgres): support add schema as prefix of table name

dialect_postgres.go, engine.go
=> fix: add const value for public scheam name of postgres.

session_get_test.go
go-xorm/core@f43c33d9a48db006417a7ac4c16b08897e3e1458  will fix #811 and this PR will add test for that.
=> Add test for (id) replace

session_find.go, session_query.go, session_stats_test.go, statement.go
=> Add test for count with orderby and limit

helpers.go, session_cols.go, session_get_test.go, session_insert.go, session_query.go, session_update.go, statement.go
=> Fix id condition not used bug

session_update_test.go
=> Add test for update map

engine_table_test.go
=> Add test for tablename

engine_cond.go, error.go, interface.go, session.go, session_cols_test.go
=> add test and remove unused warn log

engine_table.go, session_find.go, session_find_test.go, session_insert.go, statement.go
=> fix tablename bug

engine.go, interface.go, session_delete.go, session_find.go, session_get.go, session_insert.go, session_update.go, session_update_test.go, statement.go, tag_cache_test.go, xorm.go
=> fix update map with table name

session_insert_test.go
=> add test for insert anonymous struct

engine.go, session_find_test.go
=> fix some bug on extends find

session_find_test.go, xorm.go
=> Cache limit test

session_find_test.go, session_schema.go, session_schema_test.go
=> fix tablename bug when sync2

error.go, session.go, session_find_test.go
=> Add more test for join find

session_tx.go, session_tx_test.go
=> Add support for mulitple transactions on one session

migrate/migrate.go
=> refactor(migrate): just return error instead.

examples/goroutine.go
engine.ShowSQL is a method, not variable anymore
=> Fix compile error

session.go, session_insert.go, session_update.go, tag_version_test.go
fix panic when use version with uint32 type #1124
=> Add version uint type support

error.go, session_delete.go, session_exist.go, session_find.go, session_get.go, session_iterate.go, session_update.go, session_update_test.go, statement.go
=> Add lasterror on statement to return errors when chain operations

rows_test.go
=> add more tests for rows

dialect_mssql.go, dialect_mssql_test.go
=> fix mssql connstr bug

session_update.go, session_update_test.go
=> add deleted condition for Update operation

engine_cond.go, json.go, session.go, session_convert.go, statement.go, types_test.go
=> Make json handler as interface

engine_group.go
=> add func (eg *EngineGroup) Context(ctx context.Context) *Session

json.go
Let defaultJsonHandler be a json handler interface.
=> Let defaultJsonHandler be a json handler interface.

session_insert_test.go
=> Add insert multi omit tests
